import pygame

pygame.init()

WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
RED = (255, 0, 0)
YELLOW = (255, 255, 0)

UP = 'UP'
DOWN = 'DOWN'
RIGHT = 'RIGHT'
LEFT = 'LEFT'
UP_LEFT = 'UP_LEFT'
UP_RIGHT = 'UP_RIGHT'
DOWN_LEFT = 'DOWN_LEFT'
DOWN_RIGHT = 'DOWN_RIGHT'
JUMP = 'JUMP'

SQRT_2 = 1.414

HOME_TEAM = 'home'
AWAY_TEAM = 'away'

WALK = 'walk'
PASS = 'pass'
DRIBBLE = 'dribble'
SHOOT = 'shoot'

FPS = 60

WIDTH, HEIGHT = 1400, 560
WINDOW_RECT = pygame.Rect(0, 0, WIDTH, HEIGHT)

BOTTOM_LEFT = (round(0.084*WIDTH),round(0.97*HEIGHT))
BOTTOM_RIGHT = (round(0.914*WIDTH),round(0.97*HEIGHT))
TOP_LEFT = (round(0.208*WIDTH),round(0.755*HEIGHT))
TOP_RIGHT = (round(0.788*WIDTH),round(0.755*HEIGHT))
PLAY_AREA_HEIGHT = BOTTOM_LEFT[1] - TOP_LEFT[1]

RECT_GAME = pygame.Rect(BOTTOM_LEFT[0], TOP_LEFT[1], BOTTOM_RIGHT[0]-BOTTOM_LEFT[0], PLAY_AREA_HEIGHT)

CENTER_X = round(0.4885*WIDTH)
CENTER_Y = round(0.8517*HEIGHT)

PLAYER_WIDTH, PLAYER_HEIGHT = 64, 80
BALL_SIZE = 16

PG = 'pg'
SG = 'sg'
SF = 'sf'
PF = 'pf'
C = 'c'

HOME_PG_ATTACK_POSITION = pygame.Rect(round(0.38*WIDTH), round(0.89*HEIGHT), round(0.01*WIDTH), round(0.01*HEIGHT))
HOME_SG_ATTACK_POSITION = pygame.Rect(round(0.13*WIDTH), round(0.95*HEIGHT), round(0.01*WIDTH), round(0.01*HEIGHT))
HOME_SF_ATTACK_POSITION = pygame.Rect(round(0.22*WIDTH), round(0.76*HEIGHT), round(0.01*WIDTH), round(0.01*HEIGHT))
HOME_PF_ATTACK_POSITION = pygame.Rect(round(0.36*WIDTH), round(0.78*HEIGHT), round(0.01*WIDTH), round(0.01*HEIGHT))
HOME_C_ATTACK_POSITION = pygame.Rect(round(0.25*WIDTH), round(0.81*HEIGHT), round(0.01*WIDTH), round(0.01*HEIGHT))
HOME_ATTACK_POSITIONS = [HOME_PG_ATTACK_POSITION, HOME_SG_ATTACK_POSITION, HOME_SF_ATTACK_POSITION, HOME_PF_ATTACK_POSITION, HOME_C_ATTACK_POSITION]

AWAY_PG_ATTACK_POSITION = pygame.Rect(round(0.6*WIDTH), round(0.89*HEIGHT), round(0.01*WIDTH), round(0.01*HEIGHT))
AWAY_SG_ATTACK_POSITION = pygame.Rect(round(0.83*WIDTH), round(0.95*HEIGHT), round(0.01*WIDTH), round(0.01*HEIGHT))
AWAY_SF_ATTACK_POSITION = pygame.Rect(round(0.76*WIDTH), round(0.76*HEIGHT), round(0.01*WIDTH), round(0.01*HEIGHT))
AWAY_PF_ATTACK_POSITION = pygame.Rect(round(0.6*WIDTH), round(0.78*HEIGHT), round(0.01*WIDTH), round(0.01*HEIGHT))
AWAY_C_ATTACK_POSITION = pygame.Rect(round(0.722*WIDTH), round(0.857*HEIGHT), round(0.01*WIDTH), round(0.01*HEIGHT))
AWAY_ATTACK_POSITIONS = [AWAY_PG_ATTACK_POSITION, AWAY_SG_ATTACK_POSITION, AWAY_SF_ATTACK_POSITION, AWAY_PF_ATTACK_POSITION, AWAY_C_ATTACK_POSITION]

LEFT_BASKET_TOPLEFT = (round(0.165*WIDTH),round(0.3535*HEIGHT))
LEFT_BASKET_WIDTH = round(0.039*WIDTH)
LEFT_BASKET_HEIGHT = round(0.0178*HEIGHT)
LEFT_BASKET_RECT = pygame.Rect(LEFT_BASKET_TOPLEFT[0], LEFT_BASKET_TOPLEFT[1], LEFT_BASKET_WIDTH, LEFT_BASKET_HEIGHT)
LEFT_GOAL_RECT = pygame.Rect(LEFT_BASKET_TOPLEFT[0], round(0.83*HEIGHT), LEFT_BASKET_WIDTH, LEFT_BASKET_HEIGHT)

RIGHT_BASKET_TOPLEFT = (round(0.792*WIDTH),round(0.3535*HEIGHT))
RIGHT_BASKET_WIDTH = round(0.039*WIDTH)
RIGHT_BASKET_HEIGHT = round(0.0178*HEIGHT)
RIGHT_BASKET_RECT = pygame.Rect(RIGHT_BASKET_TOPLEFT[0], RIGHT_BASKET_TOPLEFT[1], RIGHT_BASKET_WIDTH, RIGHT_BASKET_HEIGHT)
RIGHT_GOAL_RECT = pygame.Rect(RIGHT_BASKET_TOPLEFT[0], round(0.83*HEIGHT), RIGHT_BASKET_WIDTH, RIGHT_BASKET_HEIGHT)
